### ISSUE TITLE
Broken with DSP 0.6.17.5932

### ISSUE THREAD

**Issue by gabriel-dehan** [GreyHak/dsp-belt-reverse#1]
Hey thanks for you great mods, wanted to signal that this mod seems to be broken since today's DSP update :)

Cheers!

**Comment by Sortileger** [comment]
I have to concur GreyHak,  I loaded it today, clicked on the reverse button and got the red box of death.

﻿[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 15 plugins to load
[Info   :   BepInEx] Loading [BuildCounter 1.2.0]
[Info   :   BepInEx] Loading [MultiBuild 1.1.2]
[Info   :   BepInEx] Loading [RailgunsRetargeting 1.2.0]
[Info   :   BepInEx] Loading [FreeFoundationsFreeSoil 1.2.3]
[Info   :   BepInEx] Loading [DSPCheats 2.2.0]
[Info   :   BepInEx] Loading [DSP Belt Reverse Direction 1.0.0]
[Info   :DSP Belt Reverse Direction] Initialization complete.
[Info   :   BepInEx] Loading [DSP Drone Clearing 1.2.12]
[Info   :DSP Drone Clearing] Configuration loaded.
[Info   :DSP Drone Clearing] Initialization complete.
[Info   :   BepInEx] Loading [smol splitters 1.0.0]
[Info   :   BepInEx] Loading [Splitter Over Conveyor 2.0.1]
[Info   :   BepInEx] Loading [More Replication 1.3.1]
[Info   :   BepInEx] Loading [Copy Inserters Plug-In 1.7.0.0]
[Info   :   BepInEx] Loading [Sphere Progress Plug-In 1.0.0.0]
[Info   :   BepInEx] Loading [Item Duplicator Plug-in 1.0.0.0]
[Info   :   BepInEx] Loading [Miner Info Plugin 1.0.0.0]
[Info   :   BepInEx] Loading [Super Night Light 1.0.1]
[Message:   BepInEx] Chainloader startup complete
[Info   :Super Night Light] Mod Installing.
[Message: DSPCheats] FreeHandcraft: Disabled
[Message: DSPCheats] InstantBuild: Disabled
[Message: DSPCheats] InstantHandcraft: Disabled
[Message: DSPCheats] MechaSpeedMultiplier: Enabled
[Message: DSPCheats] NoMachineEnergy: Disabled
[Message: DSPCheats] NoMechaEnergy: Disabled
[Message: DSPCheats] NoVeinUsage: Enabled
[Message: DSPCheats] UnlockInstantly: Disabled
[Info   :DSP Drone Clearing] Configuration loaded.
[Message: DSPCheats] FreeHandcraft: Disabled
[Message: DSPCheats] InstantBuild: Disabled
[Message: DSPCheats] InstantHandcraft: Disabled
[Message: DSPCheats] MechaSpeedMultiplier: Enabled
[Message: DSPCheats] NoMachineEnergy: Disabled
[Message: DSPCheats] NoMechaEnergy: Disabled
[Message: DSPCheats] NoVeinUsage: Enabled
[Message: DSPCheats] UnlockInstantly: Disabled
[Info   :DSP Drone Clearing] Configuration loaded.
[Info   :Super Night Light] Mod Uninstalled.

**Comment by delreich** [comment]
RBoD as it looked to me:
![DSP_belt_reverse_error_20210312234441](https://user-images.githubusercontent.com/5391061/111007675-b67adf80-838f-11eb-9f2f-ff92b1684697.jpg)


```
[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 12 plugins to load
[Info   :   BepInEx] Loading [DSPAutoSorter 1.1.0.0]
[Info   :   BepInEx] Loading [BuildCounter 1.2.0]
[Info   :   BepInEx] Loading [MultiBuild 1.1.2]
[Info   :   BepInEx] Loading [FreeFoundationsFreeSoil 1.2.3]
[Info   :   BepInEx] Loading [Toggle "God Mode" on or off 1.0.0.0]
[Info   :   BepInEx] Loading [DSP Belt Reverse Direction 1.0.0]
[Info   :DSP Belt Reverse Direction] Initialization complete.
[Info   :   BepInEx] Loading [DSP God Mode Button 1.0.1]
[Info   :DSP God Mode Button] Initialization complete.
[Info   :   BepInEx] Loading [Splitter Over Conveyor 2.0.1]
[Info   :   BepInEx] Loading [No Advisor 1.1.0]
[Info   :   BepInEx] Loading [Copy Inserters Plug-In 1.7.0.0]
[Info   :   BepInEx] Loading [Starmap Buffs Plugin 1.0.0.0]
[Info   :   BepInEx] Loading [Super Night Light 1.0.1]
[Message:   BepInEx] Chainloader startup complete
[Info   :Super Night Light] Mod Installing.
[Info   :Super Night Light] Mod Uninstalled.
```

**Comment by GreyHak** [comment]
@Sortileger @delreich @gabriel-dehan Thank you for the report and the details.  I'll have an update out this weekend.  Due to the new game release VFAudio.Create call now has a new parameter which is causing the problem.  I'll let you know when the release goes out.

**Comment by GreyHak** [comment]
@Sortileger @delreich @gabriel-dehan v1.0.1 provides a rebuild to work with update 0.6.17.5932.
