### ISSUE TITLE
Reverse Error

### ISSUE THREAD

**Issue by SharerMax** [GreyHak/dsp-belt-reverse#11]
DSP Version: 0.9.25.11985
Reproduct: click reverse icon
OS:: Win 10

![image](https://user-images.githubusercontent.com/9065684/164507511-cadd47b5-3a83-4ea5-a0d4-532b455cd840.png)

**Comment by G-LiuJunYu** [comment]
Version 0.9.25.11996
The same error, please fix it as soon as possible, thanks

**Comment by GreyHak** [comment]
@SharerMax @G-LiuJunYu Issue fixed in v1.1.6.  Thank you for letting me know of the issue.
