### ISSUE TITLE
Places some amount of items on the belt into inventory when reversing full belt

### ISSUE THREAD

**Issue by Xuerian** [GreyHak/dsp-belt-reverse#2]
Seems like about half.

**Comment by GreyHak** [comment]
@Xuerian Yeah, I'd like to fix it to.  When I wrote the mod, I didn't know how to address the issue.  Now, having written the Smooth Splitter mod, I think I might know how to deal with it.

**Comment by GreyHak** [comment]
@Xuerian Fixed in v1.1.0
