### ISSUE TITLE
Bug: Reverse Belt Button Needs to be moved.

### ISSUE THREAD

**Issue by JamieRCHI** [GreyHak/dsp-belt-reverse#4]
Due to a new feature in the game that adds an icon to display what you are using the belt for, the Reverse Belt button overlapps the new one. Please move the Reverse Belt button to the left (or right) and maybe down a bit to line it up with the other one. 
Thank you.

**Comment by GreyHak** [comment]
Button moved in v1.1.1.  Thank you for the report @JamieRCHI

**Comment by JamieRCHI** [comment]
And thanks for you for the quick fix. And now to learn how to fix a mod myself. 👍
