### ISSUE TITLE
MissingMethodException: VFAudio

### ISSUE THREAD

**Issue by yozorayuki** [GreyHak/dsp-belt-reverse#6]
[Error  : Unity Log] MissingMethodException: VFAudio VFAudio.Create(string,UnityEngine.Transform,UnityEngine.Vector3,bool,int)
Stack trace:
void DSPBeltReverseDirection.DSPBeltReverseDirection.GameMain_Begin_Prefix()+<GameMain_Begin_Prefix>b__11_0() => { }
void UnityEngine.Events.InvokableCall.Invoke()
void UnityEngine.Events.UnityEvent.Invoke()
void UnityEngine.UI.Button.Press()
void UnityEngine.UI.Button.OnPointerClick(PointerEventData eventData)
void UnityEngine.EventSystems.ExecuteEvents.Execute(IPointerClickHandler handler, BaseEventData eventData)
bool UnityEngine.EventSystems.ExecuteEvents.Execute<IPointerClickHandler>(GameObject target, BaseEventData eventData, EventFunction<IPointerClickHandler> functor)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by GreyHak** [comment]
@yozorayuki  The Belt Reverse mod has now been rebuilt for DSP 0.8.22.9331. This issue should be fixed in v1.1.3. Thank you for letting me know of the issue.
