### ISSUE TITLE
Broken on 0.8.23.9808

### ISSUE THREAD

**Issue by aekoch** [GreyHak/dsp-belt-reverse#7]
Broken on 0.8.23.9808.  Here is the exception message when clicking the reverse button:

[Error  : Unity Log] MissingMethodException: VFAudio VFAudio.Create(string,UnityEngine.Transform,UnityEngine.Vector3,bool,int,int)
Stack trace:
DSPBeltReverseDirection.DSPBeltReverseDirection+<>c.<GameMain_Begin_Prefix>b__11_0 () (at <477edf5e19d34ba48e72644e1036dab2>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <ba62fd13111e45818db654d4800999fe>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <ba62fd13111e45818db654d4800999fe>:0)
UnityEngine.UI.Button.Press () (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by GreyHak** [comment]
@aekoch Thank you for the report.  v1.1.4 will now work with 0.8.23.9808.
