### ISSUE TITLE
Does not work with 0.9.24.11209

### ISSUE THREAD

**Issue by veldthui** [GreyHak/dsp-belt-reverse#9]
Does not error but nothing on UI when belt selected so can't change the direction

**Comment by GreyHak** [comment]
@veldthui Thank you for the report.  I am unable to reproduce your issue.  Are you sure you have v1.1.5 loaded?  When you enable the debug log, do you see:
[Info   :   BepInEx] Loading [DSP Belt Reverse Direction 1.1.5]
[Info   :DSP Belt Reverse Direction] Initialization complete.

**Comment by veldthui** [comment]
It said I had the right version but I uninstalled it and re-installed it and now it is working. For future how do I enable the debug log and where do I find it?
Thanks.
